import React, { useState, useRef } from 'react';
import { UploadCloud, X, FileCheck, AlertCircle } from 'lucide-react';
interface UploadModalProps { isOpen: boolean; onClose: () => void; onStartUpload: (file: File | string, instructions?: File | null) => void; mode: 'upload' | 'camera'; }
export const UploadModal: React.FC<UploadModalProps> = ({ isOpen, onClose, onStartUpload, mode }) => {
  const [isDragging, setIsDragging] = useState(false); const [instructionsFile, setInstructionsFile] = useState<File | null>(null);
  const fileInputRef = useRef<HTMLInputElement>(null); const instructionsInputRef = useRef<HTMLInputElement>(null);
  if (!isOpen) return null;
  const chooseForm = (file: File) => { if (file.name.toLowerCase().endsWith('.pdf')) onStartUpload(file, instructionsFile); };
  const handleDrop = (e: React.DragEvent) => { e.preventDefault(); setIsDragging(false); const file = e.dataTransfer.files?.[0]; if (file) chooseForm(file); };
  const handleFileChange = (e: React.ChangeEvent<HTMLInputElement>) => { const file = e.target.files?.[0]; if (file) chooseForm(file); };
  const handlePresetSelect = (name: string) => onStartUpload(name);
  return <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/60 dark:bg-black/80 backdrop-blur-md animate-in fade-in duration-200" role="dialog" aria-modal="true">
    <div className="relative w-full max-w-xl bg-white dark:bg-[#1E2220] border border-[#CEF1E4] dark:border-[rgba(206,241,228,0.15)] rounded-3xl shadow-2xl overflow-hidden p-6 sm:p-8 animate-in zoom-in-95 duration-300 transition-colors">
      <button onClick={onClose} className="absolute top-5 right-5 p-2 rounded-full text-[#6B706D] dark:text-[#ACAFAB] hover:text-[#2E2E2E] dark:hover:text-white hover:bg-[#CEF1E4]/50 dark:hover:bg-[#383D3A] transition-colors" aria-label="Close modal"><X className="w-5 h-5" /></button>
      <div className="mb-6"><div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-[#CCF0E6] dark:bg-[#2E2E2E] text-[#2EB688] text-xs font-mono uppercase mb-2">{mode === 'camera' ? 'Camera Capture' : 'Document Ingestion'}</div><h3 className="text-2xl font-bold text-[#2E2E2E] dark:text-white font-sans">{mode === 'camera' ? 'Take a Document Photo' : 'Upload Government Form'}</h3><p className="mt-1 text-sm text-[#6B706D] dark:text-[#ACAFAB]">Upload the government form PDF; official instructions are optional supplementary evidence.</p></div>
      <div onDragOver={(e) => { e.preventDefault(); setIsDragging(true); }} onDragLeave={() => setIsDragging(false)} onDrop={handleDrop} onClick={() => fileInputRef.current?.click()} className={`relative border-2 border-dashed rounded-2xl p-8 sm:p-10 flex flex-col items-center justify-center text-center cursor-pointer transition-all duration-300 ${isDragging ? 'border-[#2EB688] bg-[#2EB688]/10 scale-[1.01]' : 'border-[#CEF1E4] dark:border-[rgba(206,241,228,0.15)] hover:border-[#2EB688] bg-[#F0FAF6] dark:bg-[#111214]'}`}>
        <input type="file" ref={fileInputRef} onChange={handleFileChange} accept=".pdf" className="hidden" /><div className="w-16 h-16 rounded-2xl bg-[#CCF0E6]/50 dark:bg-[#2E2E2E] border border-[#CEF1E4] flex items-center justify-center text-[#2EB688] mb-4"><UploadCloud className="w-8 h-8" /></div><p className="text-base font-semibold text-[#2E2E2E] dark:text-white">Click to browse or drag & drop</p><p className="mt-1 text-xs text-[#6B706D] dark:text-[#ACAFAB] font-mono">Government form PDF (required, up to 25 MB)</p><button type="button" className="mt-5 px-4 py-2 rounded-lg bg-[#2EB688] hover:bg-[#259B73] text-xs font-mono text-white">Browse Local Files</button>
      </div>
      <div className="mt-4 flex items-center justify-between gap-3 p-3 rounded-xl bg-[#F0FAF6] dark:bg-[#111214] border border-[#CEF1E4] dark:border-[rgba(206,241,228,0.15)]"><div className="min-w-0"><div className="text-xs font-semibold text-[#2E2E2E] dark:text-white">Official Instructions <span className="font-normal text-[#6B706D]">(optional)</span></div><div className="text-[10px] font-mono text-[#6B706D] dark:text-[#ACAFAB] truncate">{instructionsFile?.name || 'Add a supplementary PDF for stronger evidence'}</div></div><input ref={instructionsInputRef} type="file" accept=".pdf" className="hidden" onChange={(e) => setInstructionsFile(e.target.files?.[0] || null)} /><button type="button" onClick={(e) => { e.stopPropagation(); instructionsInputRef.current?.click(); }} className="shrink-0 px-3 py-1.5 rounded-lg border border-[#2EB688]/40 text-[#2EB688] text-[10px] font-mono">Add PDF</button></div>
      <div className="mt-6 pt-4 border-t border-[#CEF1E4] dark:border-[rgba(206,241,228,0.12)]"><span className="text-xs font-mono uppercase text-[#6B706D] dark:text-[#ACAFAB] block mb-2">Or quick demo with sample official forms:</span><div className="flex flex-wrap gap-2"><button onClick={() => handlePresetSelect('Standard_Application_Form_4B_2026.pdf')} className="px-3 py-1.5 rounded-lg bg-[#F0FAF6] dark:bg-[#2E2E2E] border border-[#CEF1E4] text-xs font-mono text-[#2E2E2E] dark:text-white flex items-center gap-1.5"><FileCheck className="w-3.5 h-3.5 text-[#2EB688]" /><span>Form 4-B (Demo)</span></button></div></div>
      <div className="mt-4 flex items-center gap-2 text-[11px] text-[#6B706D] dark:text-[#ACAFAB] font-mono"><AlertCircle className="w-3.5 h-3.5 text-[#2EB688]" /><span>Live uploads are processed by the real EasyForm AI backend; demo presets stay local.</span></div>
    </div>
  </div>;
};
